// Traced Diagnosis Agent — wraps diagnosisAgent with Langfuse span tracing
// =========================================================================
// The underlying streamDiagnosis() is NOT modified.
// This wrapper adds observability only.
//
// If no parentTrace is supplied the function falls back to the untraced
// original so that the app continues to work without a Langfuse key.

import { streamDiagnosis } from './diagnosisAgent.js'

/**
 * streamDiagnosisWithTracing
 *
 * @param {string}   apiKey       — OpenAI API key
 * @param {object}   engine       — engine object from ENGINES data
 * @param {string}   sensorReport — generated by sensorAgent
 * @param {Function} onChunk      — streaming callback (same as streamDiagnosis)
 * @param {object}   parentTrace  — Langfuse trace object (optional)
 * @returns {{ diagnosisText: string, kbCallLog: Array }}
 */
export async function streamDiagnosisWithTracing(
  apiKey,
  engine,
  sensorReport,
  onChunk,
  parentTrace,
) {
  // ── No tracing if Langfuse is not configured ──────────────────────────────
  if (!parentTrace) {
    return streamDiagnosis(apiKey, engine, sensorReport, onChunk)
  }

  const span = parentTrace.span({
    name:  'diagnosis_agent',
    input: {
      engine_id:          engine.id,
      engine_name:        engine.name,
      rul:                engine.rul,
      anomaly_score:      engine.anomalyScore,
      sensor_report_size: sensorReport.length,
    },
  })

  try {
    let charsStreamed = 0

    const result = await streamDiagnosis(apiKey, engine, sensorReport, (chunk) => {
      charsStreamed += chunk.length
      onChunk(chunk)
    })

    // Log each KB query as a separate span event for audit trail visibility
    if (result.kbCallLog && result.kbCallLog.length > 0) {
      result.kbCallLog.forEach((call, idx) => {
        span.event({
          name:   `kb_query_${idx + 1}`,
          input:  { query: call.query, iteration: call.iteration },
          output: { result: call.result },
        })
      })
    }

    span.end({
      output: {
        diagnosis_length: result.diagnosisText.length,
        kb_call_count:    result.kbCallLog?.length ?? 0,
        chars_streamed:   charsStreamed,
      },
    })

    return result
  } catch (error) {
    span.end({
      output: { error: error.message },
      level:  'ERROR',
    })
    throw error
  }
}
